# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-23 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('age', models.IntegerField(default=0)),
                ('min_hours', models.IntegerField(default=4)),
                ('phonenumber', models.IntegerField()),
                ('featured', models.BooleanField(default=False)),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(default='./static/images/img_10_sq', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['location'],
            },
        ),
        migrations.CreateModel(
            name='pro_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_skills', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
            ],
            options={
                'ordering': ['rate'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('driver_first_name', models.CharField(max_length=60)),
                ('driver_last_name', models.CharField(max_length=60)),
                ('driver_phonenumber', models.IntegerField()),
                ('driver_rate', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('client_first_name', models.CharField(max_length=60)),
                ('client_last_name', models.CharField(max_length=60)),
                ('booked_hours', models.IntegerField()),
                ('total_cost', models.IntegerField(default=1600)),
                ('payment_status', models.CharField(default='Completed', editable=False, max_length=200)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Location'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pro_skills',
            field=models.ManyToManyField(to='driver.pro_skills'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Rate'),
        ),
    ]
